name: nursemovil
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mongo_dart: ^0.10.4
  googleapis: 14.0.0
  google_sign_in: ^6.0.0
  http: 1.0.0
  table_calendar: ^3.0.9
  shared_preferences: ^2.0.15
  pdf: ^3.6.0
  path_provider: ^2.0.11
  flutter_pdfview: ^1.0.0
  printing: ^5.12.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/secrets/
    - assets/images/icon.png